name: "driver_config"
description: "This analysis runs a hybrid plant to match the first example in H2Integrate"

general:
  folder_output: outputs

general:
  folder_output: ex_28_out
  create_om_reports: false
driver:
  design_of_experiments:
    flag: true
    debug_print: false
    generator: "csvgen"
    filename: "ned_reduced_sitelist_rates.csv"
    run_parallel: False
design_variables:
  site:
    latitude:
      flag: True
      units: "deg"
      lower: -90.0
      upper: 90.0
    longitude:
      flag: True
      units: "deg"
      lower: -180.0
      upper: 180.0
  iron_transport:
    latitude:
      flag: True
      units: "deg"
      lower: -90.0
      upper: 90.0
    longitude:
      flag: True
      units: "deg"
      lower: -180.0
      upper: 180.0
  grid_feedstock:
    price:
      flag: True
      units: "USD/MW"
      lower: 0
      upper: 1000
  ewin_grid_feedstock:
    price:
      flag: True
      units: "USD/kW"
      lower: 0
      upper: 1000
objective:
  name: finance_subgroup_sponge_iron.LCOS
recorder:
    file: cases.sql
    overwrite_recorder: true
    flag: true
    includes: ['site.latitude','site.longitude','iron_transport.iron_transport_cost','finance_subgroup_sponge_iron.LCOS']
    excludes: ['*']
