name: "technology_config"
description: "Set up technology for an iron mine/iron electrowinning system"

technologies:

  # iron:
  #   performance_model:
  #     model: "iron"
  #   model_inputs:
  #     cost_parameters:
  #       # h2_kgpy: 68583942.6460997 #1000000 #68583942.6460997
  #       LCOE: 58.02 #$/MWh
  #       LCOH: 7.10 #$/kg
  #       ROM_iron_site_name: "Hibbing" #"Hibbing", "Northshore", "United", "Minorca" or "Tilden"
  #       iron_ore_product_selection: "drg_taconite_pellets" #"drg_taconite_pellets" or "std_taconite_pellets"
  #       reduced_iron_product_selection: "h2_dri" #"h2_dri" or "ng_dri"
  #       structural_iron_product_selection: "eaf_steel" #"eaf_steel" or "none"
  #       structural_iron_product_selection: "none" #"eaf_steel" or "none"
  #       cost_year: 2020
  #       reduced_iron_site_latitude: 41.717
  #       reduced_iron_site_longitude: -88.398
  #       transport_cost_included: True
  #       ng_mod: False
  #       ng_price: 4
  #       capex_mod: False
  #       capex_mod_pct: 0

  grid_feedstock: #electricity feedstock for iron ore - comes from grid
    performance_model:
      model: "feedstock_performance"
    cost_model:
      model: "feedstock_cost"
    model_inputs:
      shared_parameters:
        feedstock_type: "electricity"
        units: "MW"
      performance_parameters:
        rated_capacity: 30.
      cost_parameters:
        cost_year: 2022
        price: 0 #USD/MW
        annual_cost: 0.
        start_up_cost: 0.

  mine_feedstock: #crude iron ore feedstock - comes from the ground
    performance_model:
      model: "feedstock_performance"
    cost_model:
      model: "feedstock_cost"
    model_inputs:
      shared_parameters:
        feedstock_type: "crude_ore"
        units: "t/h"
      performance_parameters:
        rated_capacity: 2000.
      cost_parameters:
        cost_year: 2022
        price: 0.0
        annual_cost: 0.
        start_up_cost: 0.

  iron_mine: # iron mine - turns crude_iron into iron_ore
    performance_model:
      model: "iron_mine_performance_martin"
    cost_model:
      model: "iron_mine_cost_martin"
    model_inputs:
      shared_parameters:
        mine: "Northshore"
        taconite_pellet_type: "std"
        max_ore_production_rate_tonnes_per_hr: 250

  iron_transport: # ship iron_ore from iron_mine to iron_plant
    performance_model:
      model: "iron_transport_performance"
    cost_model:
      model: "iron_transport_cost"
    model_inputs:
      performance_parameters:
        find_closest_ship_site: False
        shipment_site: "Chicago"
      cost_parameters:
        transport_year: 2022
        cost_year: 2022

  ewin_grid_feedstock: #electricity feedstock for iron electrowinning
    performance_model:
      model: "feedstock_performance"
    cost_model:
      model: "feedstock_cost"
    model_inputs:
      shared_parameters:
        feedstock_type: "electricity"
        units: "kW"
      performance_parameters:
        rated_capacity: 600000.
      cost_parameters:
        cost_year: 2022
        price: 0.01 #USD/kW
        annual_cost: 0.
        start_up_cost: 0.

  iron_plant: # iron plant - turns iron_ore into sponge_iron
    performance_model:
      model: "humbert_electrowinning_performance"
    cost_model:
      model: "humbert_stinn_electrowinning_cost"
    model_inputs:
      shared_parameters:
        electrolysis_type: "moe"
      performance_parameters:
        ore_fe_wt_pct: 65
        capacity_mw: 578
